apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-passport-status-api
spec:
  rules:
    - host: passport-status-api.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passport-status-api
                port:
                  name: http